[package]
name = "player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
framebuffer = "0.3.1"
ctrlc = { version = "3.2.2", features = ["termination"] }
ac-ffmpeg = "0.17.4"